# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target ‘atmatm’ do
  use_frameworks!
  pod 'NetworkStack'
  pod 'RealmSwift'
  pod 'Reusable'
  pod 'ObjectMapper'
  pod 'SwiftLint'
  pod 'SwiftGen'
  pod 'RxSwift'
  pod 'RxCocoa'

  target ‘atmatmTests’ do
    inherit! :search_paths
    # Pods for testing
  pod 'RxBlocking'  
  pod 'RxTest' 
  pod 'Quick' 
  pod 'Nimble' 
  end

  target ‘atmatmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
