/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Address: Object {

  enum Attributes: String {
    case city = "city"
    case formatted = "formatted"
    case zip = "zip"
  }

  @objc dynamic var city: String?
  @objc dynamic var formatted: String?
  @objc dynamic var zip: String?

}
