/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Atm: Object {

  enum Attributes: String {
    case sonectId = "sonectId" /* Primary Key */
    case category = "category"
    case categoryText = "categoryText"
    case imagePath = "imagePath"
    case latitude = "latitude"
    case longitude = "longitude"
    case name = "name"
    case tagline = "tagline"
  }

  enum Relationships: String {
    case address = "address"
    case openingHours = "openingHours"
  }

  @objc dynamic var sonectId: String? /* Primary Key */
  @objc dynamic var category: String?
  @objc dynamic var categoryText: String?
  @objc dynamic var imagePath: String?
  @objc dynamic var latitude: String?
  @objc dynamic var longitude: String?
  @objc dynamic var name: String?
  @objc dynamic var tagline: String?
  @objc dynamic var address: Address?
  @objc dynamic var openingHours: OpeningHours?

  override static func primaryKey() -> String? {
    return "sonectId"
  }

}
