/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Atm: Object {

  enum Attributes: String {
    case category = "category"
    case categoryText = "categoryText"
    case imagePath = "imagePath"
    case latitude = "latitude"
    case longitude = "longitude"
    case name = "name"
    case sonectId = "sonectId"
    case tagline = "tagline"
  }

  @objc dynamic var category: String?
  @objc dynamic var categoryText: String?
  @objc dynamic var imagePath: String?
  @objc dynamic var latitude: String?
  @objc dynamic var longitude: String?
  @objc dynamic var name: String?
  @objc dynamic var sonectId: String?
  @objc dynamic var tagline: String?

}
