/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class OpeningHours: Object {

  enum Attributes: String {
    case active = "active"
  }

  enum Relationships: String {
    case friday = "friday"
    case monday = "monday"
    case saturday = "saturday"
    case thursday = "thursday"
    case tuesday = "tuesday"
    case wednesday = "wednesday"
  }

  let active = RealmOptional<Bool>()
  @objc dynamic var friday: OpeningHoursByDay?
  @objc dynamic var monday: OpeningHoursByDay?
  @objc dynamic var saturday: OpeningHoursByDay?
  @objc dynamic var thursday: OpeningHoursByDay?
  @objc dynamic var tuesday: OpeningHoursByDay?
  @objc dynamic var wednesday: OpeningHoursByDay?

}
