/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class OpeningHoursByDay: Object {

  enum Attributes: String {
    case close = "close"
    case open = "open"
  }

  @objc dynamic var close: String?
  @objc dynamic var open: String?

}
