/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class OverallRating: Object {

  enum Attributes: String {
    case five = "five"
    case four = "four"
    case one = "one"
    case three = "three"
    case two = "two"
  }

  let five = RealmOptional<Int64>()
  let four = RealmOptional<Int64>()
  let one = RealmOptional<Int64>()
  let three = RealmOptional<Int64>()
  let two = RealmOptional<Int64>()

}
