/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Ratings: Object {

  enum Relationships: String {
    case all = "all"
    case overall = "overall"
  }

  var all = List<Rating>()
  @objc dynamic var overall: OverallRating?

}
