/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Rating: Object {

  enum Attributes: String {
    case by = "by"
    case comment = "comment"
    case date = "date"
    case rating = "rating"
  }

  @objc dynamic var by: String?
  @objc dynamic var comment: String?
  @objc dynamic var date: String?
  let rating = RealmOptional<Int64>()

}
