/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Address: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.city <- map["city"]
    self.formatted <- map["formatted"]
    self.zip <- map["zip"]
  }
}
