/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension OpeningHoursByDay: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.close <- map["close"]
    self.open <- map["open"]
  }
}
