/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension OpeningHours: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.active.value <- map["active"]

    // MARK: Relationships
    self.friday <- map["friday"]
    self.monday <- map["monday"]
    self.saturday <- map["saturday"]
    self.thursday <- map["thursday"]
    self.tuesday <- map["tuesday"]
    self.wednesday <- map["wednesday"]
  }
}
