/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension OverallRating: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.five.value <- map["5"]
    self.four.value <- map["4"]
    self.one.value <- map["1"]
    self.three.value <- map["3"]
    self.two.value <- map["2"]
  }
}
