/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Ratings: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {

    // MARK: Relationships
    self.all <- (map["all"], ListTransform<Rating>())
    self.overall <- map["overall"]
  }
}
