/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Rating: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.by <- map["by"]
    self.comment <- map["comment"]
    self.date <- map["date"]
    self.rating.value <- map["rating"]
  }
}
